# @package _group_
_target_: satflow.models.cloudgan.CloudGAN
forecast_steps: 6
input_channels: 12
lr: 0.0002
beta1: 0.5
beta2: 0.999
num_filters: 128
generator_model: "runet"
norm: "batch"
use_dropout: false
discriminator_model: "enhanced"
discriminator_layers: 0
loss: "vanilla"
scheduler: "cosine"
lr_epochs: 10
lambda_l1: 5
channels_per_timestep: 16
