# @package _group_
_target_: satflow.data.datamodules.SatFlowDataModule

batch_size: 16
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "satflow-flow-144-tiled-{00001..00105}.tar"
  val: "satflow-flow-144-tiled-{00106..00129}.tar"
  test: "satflow-flow-144-tiled-{00130..00149}.tar"
num_workers: 12
pin_memory: True
config:
  visualize: False
  num_timesteps: 6
  skip_timesteps: 1
  forecast_times: 12
  output_shape: 128
  target_type: "cloudmask"
  num_crops: 10
  use_topo: True
  use_latlon: True
  use_time: False
  time_aux: False
  use_mask: False
  use_image: True
  time_as_channels: False
  add_pixel_coords: False
  bands:
    [
      "HRV",
      "IR016",
      "IR039",
      "IR087",
      "IR097",
      "IR108",
      "IR120",
      "IR134",
      "VIS006",
      "VIS008",
      "WV062",
      "WV073",
    ]
  transforms: {}
