_target_: satflow.data.datamodules.SatFlowDataModule

temp_path: "."
n_train_data: 24900
n_val_data: 1000
cloud: "gcp"
num_workers: 8
pin_memory: True
configuration_filename: "satflow/configs/local.yaml"
fake_data: False
history_minutes: 30
forecast_minutes: 120
