_target_: satflow.data.datamodules.SatFlowDataModule

temp_path: "."
n_train_data: 24900
n_val_data: 1000
cloud: "local"
num_workers: 8
pin_memory: True
configuration_filename: "satflow/configs/configurations/local.yaml"
fake_data: False
required_keys:
  - sat_data
  - sat_x_coords
  - sat_y_coords
history_minutes: 10
forecast_minutes: 5
