# @package _group_
_target_: satflow.data.datamodules.SatFlowDataModule

batch_size: 4
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "satflow-flow-144-tiled-{00001..00105}.tar"
  val: "satflow-flow-144-tiled-{00106..00129}.tar"
  test: "satflow-flow-144-tiled-{00130..00149}.tar"
num_workers: 12
pin_memory: True
config:
  visualize: False
  num_timesteps: 3
  skip_timesteps: 1
  forecast_times: 12
  output_shape: 256
  target_type: "cloudmask"
  num_crops: 10
  num_times: 15
  use_topo: False
  use_latlon: False
  use_time: False
  time_aux: False
  use_mask: False
  use_image: True
  time_as_channels: False
  add_pixel_coords: False
  add_polar_coords: False
  bands: ["HRV"]
  transforms: {}
