_target_: satflow.data.datamodules.FileDataModule

batch_size: 4
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "preprocessed_satflow_prev6"
  val: "preprocessed_satflow_prev6"
  test: "preprocessed_satflow_prev6"
num_workers: 16
pin_memory: True
config:
  visualize: False
  num_timesteps: 6
  skip_timesteps: 1
  forecast_times: 48
  output_shape: 128
  target_type: "cloudmask"
  num_crops: 10
  use_topo: True
  use_latlon: False
  use_time: True
  time_aux: False
  use_mask: False
  use_image: True
  time_as_channels: False
  add_pixel_coords: False
  bands:
    [
      "HRV",
      "IR016",
      "IR039",
      "IR087",
      "IR097",
      "IR108",
      "IR120",
      "IR134",
      "VIS006",
      "VIS008",
      "WV062",
      "WV073",
    ]
  transforms: {}
